"""add missing models

Revision ID: 6615e9eef530
Revises: e5622bed674e
Create Date: 2025-03-15 01:13:41.963440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6615e9eef530'
down_revision = 'e5622bed674e'
branch_labels = None
depends_on = None


#def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('categories', 'id',
               #existing_type=sa.NUMERIC(),
              # type_=sa.String(length=36),
               #existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###